todo/urls.py
"""
URL configuration for todo project.
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views  # Добавьте этот импорт
# from todos import views


# Подключаем файл urls.py из приложения todos через include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Включите встроенные представления аутентификации Django
    path('', include('todos.urls')), # Включаем URL для приложения todos
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),  # Добавьте этот маршрут
]

todos/urls.py
# todos/urls.py
# префикс будет в urlах /todos/

from django.urls import path
from . import views
from .views import (
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
    CustomLogoutView,
)

urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('task/new/', views.task_create, name='task_create'),
    path('task/<int:pk>/edit/', views.task_update, name='task_update'),
    path('task/<int:pk>/delete/', views.task_delete, name='task_delete'),
    path('buildings/', views.building_list, name='building_list'),
    path('buildings/new/', views.building_create, name='building_create'),
    path('buildings/<int:pk>/edit/', views.building_update, name='building_update'),
    path('buildings/<int:pk>/delete/', views.building_delete, name='building_delete'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('users/', views.users_list, name='users_list'),
    path('personal_account/', views.personal_account, name='personal_account'),
    path('building_search/', views.building_search, name='building_search'),
    path('task/<int:task_id>/commentary/new/', views.commentary_create, name='commentary_create'),
    path('commentary/<int:pk>/edit/', views.commentary_update, name='commentary_update'),
    path('commentary/<int:pk>/delete/', views.commentary_delete, name='commentary_delete'),
    path('task_list_active/', views.task_list_active, name='task_list_active'),
    path('task_list_completed/', views.task_list_completed, name='task_list_completed'),
    path('approve_user/<int:user_id>/', views.approve_user, name='approve_user'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),


]

todos/models.py
# models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    is_approved = models.BooleanField(default=False) # по дефолту не одобренный администратором
    email = models.EmailField(unique=True, blank=False, null=False)  # Обязательное поле email

class Building(models.Model): # объекты/здания
    ak = models.CharField(max_length=100)
    building_name = models.CharField(max_length=200)
    address = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.ak}. {self.building_name}"

class Task(models.Model): # задачи
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    assigned_to = models.ForeignKey('todos.CustomUser', on_delete=models.CASCADE, null=True, blank=True) # один ко многим
    building = models.ForeignKey('Building', on_delete=models.SET_NULL, null=True, blank=True) # один ко многим
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')

    def __str__(self):
        return self.title

class Commentary(models.Model): # комментарии
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='commentaries') # один ко многим
    user = models.ForeignKey('todos.CustomUser', on_delete=models.CASCADE) # один ко многим
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.task.title}"

todos/forms.py
# form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm
from .models import CustomUser, Task, Building, Commentary

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True  # Сделать поле email обязательным

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'assigned_to', 'building', 'status']

class BuildingForm(forms.ModelForm):
    class Meta:
        model = Building
        fields = ['ak', 'building_name', 'address']

class BuildingSearchForm(forms.Form):
    search = forms.CharField(label='Search', max_length=100)

class CommentaryForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Выполнено'}),
        }

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))

class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label="New password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'New password'}))
    new_password2 = forms.CharField(label="Confirm new password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm new password'}))

todos/views.py
# todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import LogoutView # для логаута
from django.contrib.auth import login, authenticate
from django.db.models import Q
from django.core.paginator import Paginator
from .models import Task, Building, Commentary, CustomUser
from .forms import TaskForm, BuildingForm, BuildingSearchForm, CommentaryForm, CustomUserCreationForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from .forms import CustomPasswordResetForm, CustomSetPasswordForm


class CustomLogoutView(LogoutView):
    next_page = 'login'  # имя URL-адреса для перенаправления после выхода

class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('password_reset_done')
    email_template_name = 'registration/password_reset_email.html'

class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('password_reset_complete')

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False  # Пользователь неактивен до подтверждения
            user.save()
            return redirect('login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})




@login_required
@permission_required('todos.change_customuser', raise_exception=True)
def approve_user(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    user.is_approved = True
    user.is_active = True  # Активируем пользователя
    user.save()
    return redirect('users_list')

@login_required
def users_list(request):
    users = CustomUser.objects.all()
    users_count = users.count()
    return render(request, 'todos/users_list.html', {'users': users, 'users_count': users_count})

# для страниц
@login_required
def task_list(request):
    search_query = request.GET.get('search')
    assigned_to_query = request.GET.get('assigned_to')
    tasks = Task.objects.all().order_by('-created_at')  # Сортировка от новой к старой

    if search_query:
        tasks = tasks.filter(title__icontains=search_query)

    if assigned_to_query:
        tasks = tasks.filter(assigned_to__username__icontains=assigned_to_query)

    users_count = CustomUser.objects.count()

    # Пагинация
    paginator = Paginator(tasks, 5)  # Показывать по 5 задач на страницу
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'todos/task_list.html', {'page_obj': page_obj, 'users_count': users_count})

@login_required
def task_list_active(request):
    search_query = request.GET.get('search')
    assigned_to_query = request.GET.get('assigned_to')
    tasks = Task.objects.filter(status='active').order_by('-created_at')  # Сортировка от новой к старой

    if search_query:
        tasks = tasks.filter(title__icontains=search_query)

    if assigned_to_query:
        tasks = tasks.filter(assigned_to__username__icontains=assigned_to_query)

    users_count = CustomUser.objects.count()

    # Пагинация
    paginator = Paginator(tasks, 5)  # Показывать по 5 задач на страницу
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'todos/task_list_active.html', {'page_obj': page_obj, 'users_count': users_count})

@login_required
def task_list_completed(request):
    search_query = request.GET.get('search')
    assigned_to_query = request.GET.get('assigned_to')
    tasks = Task.objects.filter(status='completed').order_by('-created_at')  # Сортировка от новой к старой

    if search_query:
        tasks = tasks.filter(title__icontains=search_query)

    if assigned_to_query:
        tasks = tasks.filter(assigned_to__username__icontains=assigned_to_query)

    users_count = CustomUser.objects.count()

    # Пагинация
    paginator = Paginator(tasks, 5)  # Показывать по 5 задач на страницу
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'todos/task_list_completed.html', {'page_obj': page_obj, 'users_count': users_count})


@login_required
@permission_required('todos.add_task', raise_exception=True)
def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm()
    return render(request, 'todos/task_form.html', {'form': form})

@login_required
@permission_required('todos.change_task', raise_exception=True)
def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm(instance=task)
    return render(request, 'todos/task_form.html', {'form': form})

@login_required
@permission_required('todos.delete_task', raise_exception=True)
def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        task.delete()
        return redirect('task_list')
    return render(request, 'todos/task_confirm_delete.html', {'task': task})

@login_required
def building_list(request):
    ak_search = request.GET.get('ak_search')
    name_search = request.GET.get('name_search')
    buildings = Building.objects.all()

    if ak_search:
        buildings = buildings.filter(ak__icontains=ak_search) # поиск
    if name_search:
        buildings = buildings.filter(building_name__icontains=name_search)

    paginator = Paginator(buildings, 5)  # Показывать по 5 зданий на страницу
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'todos/building_list.html', {'page_obj': page_obj})
@login_required
@permission_required('todos.add_building', raise_exception=True)
def building_create(request):
    if request.method == 'POST':
        form = BuildingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('building_list')
    else:
        form = BuildingForm()
    return render(request, 'todos/building_form.html', {'form': form})

@login_required
@permission_required('todos.change_building', raise_exception=True)
def building_update(request, pk):
    building = get_object_or_404(Building, pk=pk)
    if request.method == 'POST':
        form = BuildingForm(request.POST, instance=building)
        if form.is_valid():
            form.save()
            return redirect('building_list')
    else:
        form = BuildingForm(instance=building)
    return render(request, 'todos/building_form.html', {'form': form})

@login_required
@permission_required('todos.delete_building', raise_exception=True)
def building_delete(request, pk):
    building = get_object_or_404(Building, pk=pk)
    if request.method == 'POST':
        building.delete()
        return redirect('building_list')
    return render(request, 'todos/building_confirm_delete.html', {'building': building})

@login_required
def about(request):
    return render(request, 'todos/about.html')

@login_required
def personal_account(request):
    return render(request, 'todos/personal_account.html', {'user': request.user})

@login_required
def building_search(request):
    form = BuildingSearchForm(request.GET)
    buildings = Building.objects.all()
    if form.is_valid():
        search = form.cleaned_data.get('search') # поиск
        buildings = buildings.filter(
            Q(ak__icontains=search) |
            Q(building_name__icontains=search) |
            Q(address__icontains=search)
        )
    return render(request, 'todos/building_search.html', {'form': form, 'buildings': buildings})

@login_required
def commentary_create(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        form = CommentaryForm(request.POST)
        if form.is_valid():
            commentary = form.save(commit=False)
            commentary.task = task
            commentary.user = request.user
            commentary.save()
            return redirect('task_list')
    else:
        form = CommentaryForm()
    return render(request, 'todos/commentary_form.html', {'form': form, 'task': task})

@login_required
@permission_required('todos.change_commentary', raise_exception=True)
def commentary_update(request, pk):
    commentary = get_object_or_404(Commentary, pk=pk)
    if request.method == 'POST':
        form = CommentaryForm(request.POST, instance=commentary)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = CommentaryForm(instance=commentary)
    return render(request, 'todos/commentary_form.html', {'form': form, 'commentary': commentary})

@login_required
@permission_required('todos.delete_commentary', raise_exception=True)
def commentary_delete(request, pk):
    commentary = get_object_or_404(Commentary, pk=pk)
    if request.method == 'POST':
        commentary.delete()
        return redirect('task_list')

todos/templates/todos/about.html
<!--todos/templates/todos/about.html-->
{% extends 'todos/base.html' %}

{% block title %}О нас{% endblock %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h1 class="text-center">О нас</h1>
                <h3 class="text-center mt-3">Сайт django-проекта TO-DO_List<br>Разработал студент группы Python-316<br>Компьютерной Академии Топ<br>Михайличенко Алексей.</h3>
                <div class="mt-3">
                    <a href="https://rostov.top-academy.ru/" target="_blank">
                        <img src="{% static 'todos/images/logo_top.jpg' %}" alt="Logo Top Academy" class="img-fluid" style="max-width: 300px;">
                    </a>
                </div>
                <div class="mt-3">
                    <a href="https://t.me/Aleksey_Mich" target="_blank" class="btn btn-primary">
                        <i class="bi bi-telegram"></i> Telegram
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

todos/templates/todos/base.html
<!--todos/templates/todos/base.html-->
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}TO-DO_List{% endblock %}</title>
    {% load static %}
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'todos/css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'task_list' %}">TO-DO_List</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'task_list' %}">Все задачи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'task_list_active' %}">Активные задачи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'task_list_completed' %}">Выполненные задачи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'building_list' %}">Объекты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users_list' %}">Пользователи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'personal_account' %}">Личный кабинет</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link nav-link">
                                <i class="bi bi-box-arrow-right"></i>
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Авторизация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        &copy; Разработка сайта. Михайличенко А.В., 2024
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Custom JS -->
    <script src="{% static 'todos/js/scripts.js' %}"></script>
</body>
</html>

todos/templates/todos/building_confirm_delete.html
<!--todos/templates/todos/building_confirm_delete.html-->
{% extends 'todos/base.html' %}

{% block title %}Подтвердите удаление{% endblock %}

{% block content %}
    <h1>Подтвердите удаление</h1>
    <p>Вы уверены, что хотите удалить "{{ building.building_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Подтвердить</button>
    </form>
{% endblock %}

todos/templates/todos/building_form.html
<!--todos/templates/todos/building_form.html-->
{% extends 'todos/base.html' %}

{% block title %}{% if form.instance.pk %}Редактировать объект{% else %}Добавить объект{% endif %}{% endblock %}

{% block content %}
    <h1>{% if form.instance.pk %}Edit Building{% else %}Добавить объект{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_ak">AK</label>
            {{ form.ak }}
        </div>
        <div class="form-group">
            <label for="id_building_name">Название объекта</label>
            {{ form.building_name }}
        </div>
        <div class="form-group">
            <label for="id_address">Адрес</label>
            {{ form.address }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'building_list' %}" class="btn btn-secondary">Отменить</a>
    </form>
{% endblock %}

todos/templates/todos/building_list.html
<!--todos/templates/todos/building_list.html-->
{% extends 'todos/base.html' %}

{% block title %}Все объекты{% endblock %}

{% block content %}
    <h1>Все объекты</h1>
    <p>Buildings: {{ page_obj.paginator.count }}</p>

    <!-- Поиск по полям AK и названию -->
    <form method="get" class="form-inline justify-content-center mb-3">
        <div class="form-group mx-sm-3 mb-2">
            <label for="ak_search" class="sr-only">Поиск по AK</label>
            <input type="text" class="form-control" id="ak_search" name="ak_search" placeholder="Поиск по AK">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label for="name_search" class="sr-only">Поиск по названию</label>
            <input type="text" class="form-control" id="name_search" name="name_search" placeholder="Поиск по названию">
        </div>
        <button type="submit" class="btn btn-primary mb-2">
            <i class="bi bi-search"></i>
        </button>
    </form>

    <!-- Кнопка создания нового объекта -->
    {% if perms.todos.add_building %}
        <div class="text-center mb-3">
            <a href="{% url 'building_create' %}" class="btn btn-primary">Добавить объект</a>
        </div>
    {% endif %}

    <ul class="list-group">
        {% for building in page_obj %}
            <li class="list-group-item">
                <h2><i class="bi bi-building"></i> {{ building.ak }}. {{ building.building_name }}</h2>
                <p>Address: {{ building.address }}</p>
                {% if perms.todos.change_building %}
                    <a href="{% url 'building_update' building.id %}" class="btn btn-warning btn-sm">Редактировать</a>
                {% endif %}
                {% if perms.todos.delete_building %}
                    <a href="{% url 'building_delete' building.id %}" class="btn btn-danger btn-sm">Удалить</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <!-- Пагинация -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">Первая</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Пред.</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Пред.</a>
                </li>
            {% endif %}
            {% for page_number in page_obj.paginator.page_range %}
                <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">След.</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Посл.</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">След.</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

todos/templates/todos/commentary_confirm_delete.html
<!--todos/templates/todos/commentary_confirm_delete.html-->
{% extends 'todos/base.html' %}

{% block title %}Подтвердите удаление{% endblock %}

{% block content %}
    <h1>Подтвердите удаление</h1>
    <p>Вы уверены, что хотите удалить этот комментарий?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Подтвердить</button>
        <a href="{% url 'task_list' %}" class="btn btn-secondary">Отменить</a>
    </form>
{% endblock %}

todos/templates/todos/commentary_form.html
<!--todos/templates/todos/commentary_form.html-->
{% extends 'todos/base.html' %}

{% block title %}{% if commentary %}Редактировать комментарий{% else %}Add Commentary{% endif %}{% endblock %}

{% block content %}
    <h1>{% if commentary %}Редактировать комментарий{% else %}Add Commentary{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_text">Текст</label>
            {{ form.text }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
        <a href="{% url 'task_list' %}" class="btn btn-secondary">Отменить</a>
    </form>
{% endblock %}

todos/templates/todos/personal_account.html
<!--todos/templates/todos/personal_account.html-->
{% extends 'todos/base.html' %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="text-center">Аккаунт</h1>
                <h3 class="text-center">Имя пользователя: {{ user.username }}</h3>
                <h3 class="text-center">Email: {{ user.email }}</h3>
                <h3 class="text-center">Имя: {{ user.first_name }}</h3>
                <h3 class="text-center">Фамилия: {{ user.last_name }}</h3>
            </div>
        </div>
    </div>
{% endblock %}

todos/templates/todos/task_confirm_delete.html
<!--todos/templates/todos/task_confirm_delete.html-->
{% extends 'todos/base.html' %}

{% block title %}Подтверждение удаления{% endblock %}

{% block content %}
    <h1>Подтверждение удаления</h1>
    <p>Вы уверены, что хотите удалить "{{ task.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Подтвердить</button>
    </form>
{% endblock %}

todos/templates/todos/task_form.html
<!--todos/templates/todos/task_form.html-->
{% extends 'todos/base.html' %}

{% block title %}{% if form.instance.pk %}Редактировать задачу{% else %}Create Task{% endif %}{% endblock %}

{% block content %}
    <h1>{% if form.instance.pk %}Редактировать задачу{% else %}Добавить задачу{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Заголовок</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description">Описание</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_assigned_to">Кому</label>
            {{ form.assigned_to }}
        </div>
        <div class="form-group">
            <label for="id_building">Объект</label>
            {{ form.building }}
        </div>
        <div class="form-group mt-3">
            <label for="id_status">Статус</label>
            {{ form.status }}
        </div>
        <div id="building-section">
            {% if form.instance.building %}
                <p>Building: {{ form.instance.building.ak }}. {{ form.instance.building.building_name }} ({{ form.instance.building.address }})</p>
                <button type="button" id="remove-building" class="btn btn-danger btn-sm">Убрать объект</button>
            {% endif %}
            <a href="{% url 'building_search' %}" id="add-building-link" class="btn btn-primary btn-sm">Добавить объект к задаче</a>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'task_list' %}" class="btn btn-secondary">Отменить</a>
    </form>

    <script>
        document.getElementById('add-building-link').addEventListener('click', function(event) {
            event.preventDefault();
            window.open(this.href, 'buildingSearch', 'width=600,height=400');
        });

        document.getElementById('remove-building').addEventListener('click', function() {
            document.getElementById('id_building').value = '';
            document.getElementById('building-section').innerHTML = '<a href="{% url 'building_search' %}" id="add-building-link" class="btn btn-primary btn-sm">Add Building to Task</a>';
        });
    </script>
{% endblock %}